# Generated by Django 3.1.5 on 2021-01-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='title',
            new_name='nome',
        ),
    ]
