# Generated by Django 3.1.5 on 2021-01-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20210114_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='estoque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
